spring.application.name=auth-service

spring.datasource.url=jdbc:postgresql://localhost:5432/shopsphere_auth
spring.datasource.username=postgres
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

server.port=8081

eureka.enabled=true
eureka.url=http://localhost:8761/eureka
eureka.name=auth-service
eureka.host=localhost
eureka.port=${server.port}
eureka.heartbeat-interval-seconds=30

jwt.secret=c2hvcHNwaGVyZS1zZWNyZXQta2V5LWZvci1qd3QtdG9rZW4tZ2VuZXJhdGlvbi11c2UtaW4tcHJvZHVjdGlvbi1hbmQtbXVzdC1iZS1sb25nLWVub3VnaA==
jwt.expiration=86400000

app.admin.email=admin@shopsphere.com
app.admin.username=admin
app.admin.password=Zephyr!91Kite

management.endpoints.web.exposure.include=health,info,metrics,env,loggers,beans,conditions,prometheus
management.endpoint.health.show-details=always
logging.structured.format.console=logstash
